default: &default
  adapter: sqlserver
  encoding: utf8
  database: cls_platfrm_dev
  username: lester
  password: Kl74367908$ms#@74367908
  host: saturno.database.windows.net
  port: 1433
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nome_do_banco_de_dados_de_desenvolvimento
  username: seu_usuario
  password: sua_senha
  host: localhost

production:
  <<: *default
  database: cls_platfrm_dev
  username: lester
  password: Kl74367908$ms#@74367908
  host: saturno.database.windows.net
  port: 1433
  pool: 5
  timeout: 5000
